import { uploadBuffer, getBuffer } from './storage';

const RUNWAY_API_KEY = process.env.RUNWAY_API_KEY;

export interface VideoGenerationRequest {
  script: { heading: string; content: string }[];
  voiceoverUrl: string;
  style: 'cinematic' | 'documentary' | 'educational';
}

// Style prompts for different video styles
const STYLE_PROMPTS: Record<string, string> = {
  cinematic: 'cinematic, dramatic lighting, wide angle, film grain, 4k',
  documentary: 'documentary style, natural lighting, handheld camera feel, realistic',
  educational: 'clean, modern, minimal, professional, white background with graphics',
};

export async function generateVideo(request: VideoGenerationRequest): Promise<string> {
  if (!RUNWAY_API_KEY) {
    // Fallback: generate a placeholder video using script text
    return generatePlaceholderVideo(request);
  }

  // For each script section, generate a video clip
  const clips: string[] = [];

  for (const section of request.script) {
    const prompt = generateVisualPrompt(section.heading, section.content, request.style);
    const clipUrl = await generateClip(prompt);
    clips.push(clipUrl);
  }

  // In production, combine clips with FFmpeg or Runway's concat API
  // For now, return the first clip or a combined URL
  return clips[0] || generatePlaceholderVideo(request);
}

function generateVisualPrompt(heading: string, content: string, style: string): string {
  const styleModifier = STYLE_PROMPTS[style] || STYLE_PROMPTS.cinematic;

  // Generate a visual description based on the script content
  const prompt = `Visual for YouTube video section "${heading}": ${content.slice(0, 200)}. Style: ${styleModifier}. Aspect ratio 16:9.`;

  return prompt;
}

async function generateClip(prompt: string): Promise<string> {
  const response = await fetch('https://api.runwayml.com/v1/generate', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${RUNWAY_API_KEY}`,
    },
    body: JSON.stringify({
      model: 'gen3-alpha',
      prompt,
      duration: 10, // 10 seconds per clip
      width: 1280,
      height: 720,
    }),
  });

  if (!response.ok) {
    throw new Error('Runway API error');
  }

  const data = await response.json();

  // Poll for completion
  const taskId = data.id;
  let status = 'pending';
  let videoUrl = '';

  while (status === 'pending' || status === 'processing') {
    await new Promise((resolve) => setTimeout(resolve, 5000));

    const statusResponse = await fetch(`https://api.runwayml.com/v1/generations/${taskId}`, {
      headers: {
        Authorization: `Bearer ${RUNWAY_API_KEY}`,
      },
    });

    const statusData = await statusResponse.json();
    status = statusData.status;

    if (status === 'completed') {
      videoUrl = statusData.videoUrl;
    } else if (status === 'failed') {
      throw new Error('Video generation failed');
    }
  }

  return videoUrl;
}

async function generatePlaceholderVideo(request: VideoGenerationRequest): Promise<string> {
  // Create a simple HTML-based video placeholder
  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { margin: 0; padding: 40px; background: #1a1a2e; color: white; font-family: Arial; }
        h1 { color: #e94560; }
        .section { margin: 20px 0; padding: 20px; background: #16213e; border-radius: 10px; }
      </style>
    </head>
    <body>
      <h1>${request.script[0]?.heading || 'Video Content'}</h1>
      ${request.script.map(s => `
        <div class="section">
          <h2>${s.heading}</h2>
          <p>${s.content.slice(0, 300)}...</p>
        </div>
      `).join('')}
      <p style="margin-top: 40px; color: #888;">Generated by FaceFlow AI</p>
    </body>
    </html>
  `;

  const buffer = Buffer.from(html, 'utf-8');
  return uploadBuffer(buffer, `video-placeholder-${Date.now()}.html`, 'text/html');
}
