plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/manjunathkalburgi/Documents/AI_React_Projects/claude/free-claude-code/templates/ai-saas-india/gst-automation/dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "/Users/manjunathkalburgi/Documents/AI_React_Projects/claude/free-claude-code/templates/ai-saas-india/gst-automation"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]