// Sample data for the portfolio site

import { Book } from '../types/book';
import { Project } from '../types/project';
import { Experience } from '../types/experience';
import { Skill } from '../types/skill';

export const sampleProjects: Project[] = [
  {
    id: 'ai-pm-lesson-platform',
    title: 'AI Product Manager Learning Platform',
    description: 'A comprehensive learning platform for AI Product Managers featuring resume analysis, prompt engineering tools, and industry insights.',
    image: '/api/placeholder/400/300',
    technologies: ['React', 'TypeScript', 'Vite', 'Tailwind CSS', 'Framer Motion', 'FastAPI', 'OpenRouter API'],
    githubUrl: 'https://github.com/your-username/ai-pm-lesson-platform',
    liveUrl: 'https://ai-pm-learning-platform.example.com',
    featured: true,
    category: 'AI/ML Platform',
    date: '2024-01-15',
    status: 'production',
    tags: ['AI', 'Product Management', 'Learning Platform'],
  },
  {
    id: 'ats-resume-analyzer',
    title: 'ATS Resume Analyzer',
    description: 'AI-powered application that analyzes resumes against job descriptions to calculate compatibility scores and provide improvement suggestions.',
    image: '/api/placeholder/400/300',
    technologies: ['Python', 'spaCy', 'Sentence Transformers', 'FastAPI', 'React', 'Tailwind CSS'],
    githubUrl: 'https://github.com/your-username/ats-resume-analyzer',
    liveUrl: 'https://ats-resume-analyzer.example.com',
    featured: true,
    category: 'Career Tech',
    date: '2023-11-20',
    status: 'production',
    tags: ['AI', 'NLP', 'Career Tools', 'Resume Analysis'],
  },
  {
    id: 'portfolio-template',
    title: 'Developer Portfolio Template',
    description: 'A modern, responsive portfolio website template built with React and TypeScript, featuring dark mode support and smooth animations.',
    image: '/api/placeholder/400/300',
    technologies: ['React', 'TypeScript', 'Vite', 'Tailwind CSS', 'Framer Motion', 'Lucide React'],
    githubUrl: 'https://github.com/your-username/portfolio-template',
    liveUrl: 'https://portfolio-template.example.com',
    featured: true,
    category: 'Web Development',
    date: '2023-09-10',
    status: 'completed',
    tags: ['React', 'Portfolio', 'Web Development'],
  },
  {
    id: 'ai-agent-book',
    title: 'AI Agents: The Complete Guide',
    description: 'A comprehensive ebook covering LLMs, RAG, agent building, multi-agent systems, and complete end-to-end projects - all in simple words with working examples.',
    image: '/api/placeholder/400/300',
    technologies: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'GitHub Pages'],
    githubUrl: 'https://github.com/your-username/ai-agents-book',
    liveUrl: 'https://kalburgimanju.github.io/ai-code-master/books/AI-Agents/webapp/',
    featured: true,
    category: 'Educational',
    date: '2023-08-05',
    status: 'published',
    tags: ['Book', 'Educational', 'AI Agents'],
  },
  {
    id: 'cx-automation-book',
    title: 'Customer Experience Automation',
    description: 'A practical guide covering customer journey optimization, automation tools, and omnichannel customer engagement strategies.',
    image: '/api/placeholder/400/300',
    technologies: ['Next.js', 'React', 'Tailwind CSS', 'Markdown'],
    githubUrl: 'https://github.com/your-username/cx-automation-book',
    liveUrl: 'https://kalburgimanju.github.io/cx-automation/',
    featured: false,
    category: 'Educational',
    date: '2023-06-15',
    status: 'draft',
    tags: ['Book', 'Customer Experience', 'Automation'],
  },
  {
    id: 'ai-safety-experts',
    title: 'AI Safety Experts Network',
    description: 'A platform connecting AI safety researchers and practitioners for collaboration and knowledge sharing.',
    image: '/api/placeholder/400/300',
    technologies: ['React', 'TypeScript', 'Node.js', 'Express'],
    githubUrl: 'https://github.com/your-username/ai-safety-experts',
    featured: false,
    category: 'Community',
    date: '2023-04-20',
    status: 'concept',
    tags: ['AI Safety', 'Community', 'Research'],
  },
];

export const sampleBooks: Book[] = [
  {
    id: 'ai-agents',
    title: 'AI Agents: The Complete Guide',
    author: 'Manjunath Kalburgi',
    description: 'Build, Deploy, and Scale Intelligent AI Agents from Scratch - All in simple words with working examples.',
    coverImage: '/api/placeholder/400/300',
    publishedDate: '2024-01-01',
    isbn: '978-1-2345-6789-0',
    pageCount: 350,
    language: 'English',
    category: 'AI & Machine Learning',
    rating: 4.5,
    reviews: 128,
    price: {
      hardcover: '$39.99',
      paperback: '$24.99',
      ebook: '$9.99',
    },
    summary: 'A comprehensive ebook covering LLMs, RAG, agent building, multi-agent systems, tools, security, observability, and a complete end-to-end project - all in simple words with working examples.',
    tableOfContents: [
      'LLMs & GenAI Fundamentals',
      'RAG & Knowledge Systems',
      'Introduction to AI Agents',
      'Customer Support Agents',
      'Executive & Analyst Agents',
      'Developer & Coder Agents',
      'Designer & Creative Agents',
      'Multi-Agent Systems',
      'Building Tools from Scratch',
      'Building Your Own LLM Pipeline',
      'Building RAG from Scratch',
      'Complete Project: End to End',
      'Security, Safety & Guardrails',
      'Observability & Scalability',
      'Authenticity & The Future',
    ],
    chapters: [
      {
        id: 'chapter-01',
        title: 'LLMs & GenAI Fundamentals',
        summary: 'Transformers, tokenization, prompt engineering',
        wordCount: 12500,
        estimatedReadTime: 45,
        content: 'Chapter content coming soon...',
      },
      {
        id: 'chapter-02',
        title: 'RAG & Knowledge Systems',
        summary: 'Embeddings, vector databases, retrieval',
        wordCount: 15000,
        estimatedReadTime: 52,
        content: 'Chapter content coming soon...',
      },
      {
        id: 'chapter-03',
        title: 'Introduction to AI Agents',
        summary: 'Agent loops, tool use, memory, planning',
        wordCount: 18000,
        estimatedReadTime: 60,
        content: 'Chapter content coming soon...',
      },
    ],
    tags: ['AI', 'Machine Learning', 'Agents', 'LLM', 'RAG'],
    publisher: 'TechPress Publishing',
    awards: ['Best AI Book 2024'],
  },
  {
    id: 'cx-automation',
    title: 'Customer Experience Automation',
    author: 'Manjunath Kalburgi',
    description: 'A practical guide covering customer journey optimization, automation tools, and omnichannel customer engagement strategies.',
    coverImage: '/api/placeholder/400/300',
    publishedDate: '2023-03-15',
    isbn: '978-1-2345-6790-5',
    pageCount: 280,
    language: 'English',
    category: 'Business & Technology',
    rating: 4.2,
    reviews: 89,
    price: {
      hardcover: '$34.99',
      paperback: '$19.99',
      ebook: '$7.99',
    },
    summary: 'An essential guide for businesses looking to implement effective customer experience automation strategies.',
    tableOfContents: [
      'Introduction to CX Automation',
      'Customer Journey Mapping',
      'Automation Tools & Platforms',
      'Email Automation',
      'AI Chatbots & Communication',
      'Omnichannel Strategies',
      'Analytics & Implementation',
      'Case Studies',
      'Future Trends',
    ],
    chapters: [
      {
        id: 'chapter-01',
        title: 'Introduction to CX Automation',
        summary: 'Overview of customer experience automation trends',
        wordCount: 8000,
        estimatedReadTime: 30,
        content: 'Chapter content coming soon...',
      },
      {
        id: 'chapter-02',
        title: 'Customer Journey Mapping',
        summary: 'Mapping and optimizing customer journeys',
        wordCount: 12000,
        estimatedReadTime: 40,
        content: 'Chapter content coming soon...',
      },
    ],
    tags: ['Customer Experience', 'Automation', 'Business'],
    publisher: 'Business Tech Press',
    awards: [],
  },
];

export const sampleExperience: Experience[] = [
  {
    id: '1',
    title: 'Senior AI Product Manager',
    company: 'TechCorp Solutions',
    location: 'Bangalore, India',
    startDate: '2021-06-01',
    endDate: 'Present',
    description: 'Leading AI product development initiatives, building end-to-end AI agent systems, and implementing RAG solutions for enterprise clients.',
    achievements: [
      'Led development of AI-powered customer support platform',
      'Implemented RAG systems for knowledge base integration',
      'Mentored team of 5 junior product managers',
      'Reduced customer support response time by 40% through AI automation',
    ],
    technologies: ['AI Agents', 'RAG', 'Python', 'FastAPI', 'React'],
  },
  {
    id: '2',
    title: 'Product Manager - AI/ML',
    company: 'DataSphere Inc',
    location: 'Hyderabad, India',
    startDate: '2018-03-15',
    endDate: '2021-05-31',
    description: 'Managed product lifecycle for AI-powered analytics platform, including data ingestion, model training, and user-facing applications.',
    achievements: [
      'Built end-to-end MLOps pipeline',
      'Launched 3 major product updates',
      'Increased user engagement by 60%',
    ],
    technologies: ['Machine Learning', 'TensorFlow', 'AWS', 'Docker'],
  },
  {
    id: '3',
    title: 'Software Engineer',
    company: 'Innovatech Solutions',
    location: 'Pune, India',
    startDate: '2015-07-01',
    endDate: '2018-03-14',
    description: 'Developed web applications and APIs using modern JavaScript frameworks and Python.',
    achievements: [
      'Developed 10+ web applications',
      'Implemented CI/CD pipelines',
      'Improved application performance by 45%',
    ],
    technologies: ['JavaScript', 'Python', 'Node.js', 'MongoDB'],
  },
];

export const sampleSkills: Skill[] = [
  {
    id: '1',
    name: 'Python',
    category: 'Languages',
    level: 'Expert',
    proficiency: 90,
    icon: 'python',
    yearsOfExperience: 6,
  },
  {
    id: '2',
    name: 'React',
    category: 'Frontend',
    level: 'Advanced',
    proficiency: 85,
    icon: 'react',
    yearsOfExperience: 4,
  },
  {
    id: '3',
    name: 'TypeScript',
    category: 'Languages',
    level: 'Advanced',
    proficiency: 80,
    icon: 'typescript',
    yearsOfExperience: 3,
  },
  {
    id: '4',
    name: 'Node.js',
    category: 'Backend',
    level: 'Intermediate',
    proficiency: 75,
    icon: 'nodejs',
    yearsOfExperience: 3,
  },
  {
    id: '5',
    name: 'AI/ML',
    category: 'AI & ML',
    level: 'Expert',
    proficiency: 95,
    icon: 'brain',
    yearsOfExperience: 5,
  },
  {
    id: '6',
    name: 'AWS',
    category: 'DevOps',
    level: 'Advanced',
    proficiency: 78,
    icon: 'aws',
    yearsOfExperience: 3,
  },
  {
    id: '7',
    name: 'Docker',
    category: 'DevOps',
    level: 'Intermediate',
    proficiency: 72,
    icon: 'docker',
    yearsOfExperience: 2,
  },
  {
    id: '8',
    name: 'FastAPI',
    category: 'Backend',
    level: 'Advanced',
    proficiency: 82,
    icon: 'fastapi',
    yearsOfExperience: 3,
  },
  {
    id: '9',
    name: 'Tailwind CSS',
    category: 'Frontend',
    level: 'Advanced',
    proficiency: 85,
    icon: 'tailwind',
    yearsOfExperience: 2,
  },
  {
    id: '10',
    name: 'Framer Motion',
    category: 'Animation',
    level: 'Intermediate',
    proficiency: 70,
    icon: 'framer',
    yearsOfExperience: 2,
  },
  {
    id: '11',
    name: 'GitHub Actions',
    category: 'DevOps',
    level: 'Intermediate',
    proficiency: 65,
    icon: 'github',
    yearsOfExperience: 3,
  },
  {
    id: '12',
    name: 'Docker Compose',
    category: 'DevOps',
    level: 'Intermediate',
    proficiency: 68,
    icon: 'docker',
    yearsOfExperience: 2,
  },
];